### ISSUE TITLE
Ruby 2.1.2 calling open results in error

### ISSUE THREAD

**Issue by mrmanishs** [staskie/currency_switcher#6]
When using ruby 1.8.7 with open-uri, the library works. When using ruby 2.1.2 with the included open-uri, it does not and I get the following error:

Zlib::DataError: incorrect header check

Any idea?

**Comment by mrmanishs** [comment]
Dominik,

I wanted to check-in here to see if you had an update.

Thanks.

Manish

**Comment by staskie** [comment]
Hi Manish,

Work is in progress. I found the issue, fixed it, but still need to migrate tests to rspec and cut a release.

I should be done by the end of the week. Will keep you updated.

Thanks

**Comment by mrmanishs** [comment]
I'm glad you were able to reproduce the problem and locate a fix

I look forward to the update.

Thanks Dominik.

Manish

**Comment by staskie** [comment]
Hi @mrmanishs,

I just cut a new release, which should be working with ruby 2.0 and 2.1.

**Comment by mrmanishs** [comment]
Hi Dominick,

I have been out of town, so was just able to get to this.

I reinstalled the gem (currency_switcher 0.0.2), but it throws an error, any ideas?

rails console

Loading development environment (Rails 4.1.6)
2.1.2 :001 > require 'currency_switcher'
 => false 

2.1.2 :002 > 3.exchange(“usd”,”usd”)
StandardError: Could not work out the result
        from /Users/manish/.rvm/src/rvm/gems/ruby-2.1.2/gems/currency_switcher-0.0.2/lib/currency_switcher.rb:93:in `calculate_value'
        from /Users/manish/.rvm/src/rvm/gems/ruby-2.1.2/gems/currency_switcher-0.0.2/lib/currency_switcher/ext/fixnum.rb:34:in `method_missing'
        from (irb):2
        from /Users/manish/.rvm/src/rvm/gems/ruby-2.1.2@global/gems/railties-4.1.6/lib/rails/commands/console.rb:90:in `start'
        from /Users/manish/.rvm/src/rvm/gems/ruby-2.1.2@global/gems/railties-4.1.6/lib/rails/commands/console.rb:9:in `start'
        from /Users/manish/.rvm/src/rvm/gems/ruby-2.1.2@global/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:69:in `console'
        from /Users/manish/.rvm/src/rvm/gems/ruby-2.1.2@global/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
        from /Users/manish/.rvm/src/rvm/gems/ruby-2.1.2@global/gems/railties-4.1.6/lib/rails/commands.rb:17:in `<top (required)>'
        from /Users/manish/.rvm/src/rvm/gems/ruby-2.1.2/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require'
        from /Users/manish/.rvm/src/rvm/gems/ruby-2.1.2/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /Users/manish/.rvm/src/rvm/gems/ruby-2.1.2@global/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `block in require'
        from /Users/manish/.rvm/src/rvm/gems/ruby-2.1.2@global/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /Users/manish/.rvm/src/rvm/gems/ruby-2.1.2@global/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
        from /Users/manish/AcceleWeb/srcror/getmethe.com/bin/rails:8:in `<top (required)>'
        from /Users/manish/.rvm/src/rvm/gems/ruby-2.1.2@global/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in `load'
        from /Users/manish/.rvm/src/rvm/gems/ruby-2.1.2@global/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in `block in load'
        from /Users/manish/.rvm/src/rvm/gems/ruby-2.1.2@global/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /Users/manish/.rvm/src/rvm/gems/ruby-2.1.2@global/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in `load'
        from /Users/manish/.rvm/src/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/manish/.rvm/src/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'2.1.2 :003 > 

Thanks.

Manish

**Comment by staskie** [comment]
Hi there

The latest version is 0.0.3 but in the error above I see you are still using .2

Please upgrade and let me know if it is any better.

**Comment by mrmanishs** [comment]
Dominick,

It worked. I see the issue, it was on my end. 

Thank you.

Manish
